"""
dashIO pre-build script — embeds web assets as PROGMEM arrays.

Reads every file in data/dashIO/ and generates src/core/web_assets.h
with one raw PROGMEM byte array per file.

On first boot the firmware writes these arrays to the SD card, making
M5Burner installation zero-touch (no manual file copying needed).

Runs automatically via:  extra_scripts = pre:scripts/embed_assets.py
"""

import os
import glob

Import("env")  # noqa: F821

ASSETS_DIR  = os.path.join(env["PROJECT_DIR"], "data", "dashIO")  # noqa: F821
OUTPUT_FILE = os.path.join(env["PROJECT_DIR"], "src", "core", "web_assets.h")  # noqa: F821

CONTENT_TYPES = {
    ".html": "text/html",
    ".css":  "text/css",
    ".js":   "application/javascript",
    ".json": "application/json",
    ".png":  "image/png",
    ".ico":  "image/x-icon",
}

def sanitize(name):
    return name.replace(".", "_").replace("-", "_").replace("/", "_")


def generate_header():
    if not os.path.isdir(ASSETS_DIR):
        print(f"[embed_assets] Assets dir not found: {ASSETS_DIR}")
        return

    files = sorted(glob.glob(os.path.join(ASSETS_DIR, "*")))
    files = [f for f in files if os.path.isfile(f)]

    entries = []
    for filepath in files:
        filename = os.path.basename(filepath)
        ext      = os.path.splitext(filename)[1].lower()
        varname  = sanitize(filename)
        ctype    = CONTENT_TYPES.get(ext, "application/octet-stream")
        with open(filepath, "rb") as f:
            data = f.read()
        entries.append({"filename": filename, "varname": varname,
                        "ctype": ctype, "data": data})
        print(f"[embed_assets] {filename:30s} {len(data):7d} bytes")

    lines = [
        "// AUTO-GENERATED by scripts/embed_assets.py — DO NOT EDIT",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"#define WEB_ASSET_COUNT {len(entries)}",
        "",
    ]

    for e in entries:
        lines.append(f"// {e['filename']}  ({len(e['data'])} bytes)")
        lines.append(f"static const uint8_t ASSET_{e['varname']}[] PROGMEM = {{")
        hex_list = [f"0x{b:02x}" for b in e["data"]]
        for i in range(0, len(hex_list), 16):
            lines.append("  " + ", ".join(hex_list[i:i+16]) + ",")
        lines.append("};")
        lines.append(f"static const size_t ASSET_{e['varname']}_LEN = {len(e['data'])};")
        lines.append("")

    lines += [
        "struct WebAsset {",
        "  const char*    path;",
        "  const char*    content_type;",
        "  const uint8_t* data;",
        "  size_t         size;",
        "};",
        "",
        "static const WebAsset WEB_ASSETS[] PROGMEM = {",
    ]
    for e in entries:
        lines.append(
            f'  {{"/dashIO/{e["filename"]}", "{e["ctype"]}", '
            f'ASSET_{e["varname"]}, ASSET_{e["varname"]}_LEN}},'
        )
    lines += ["};", ""]

    with open(OUTPUT_FILE, "w") as f:
        f.write("\n".join(lines))

    total = sum(len(e["data"]) for e in entries)
    print(f"[embed_assets] Generated {OUTPUT_FILE}  ({total:,} bytes total in PROGMEM)")


generate_header()
